#!/usr/bin/env guile
ggspec - run a set of test suites in your project's 'spec' subdirectory.

Copyright (c) 2014 Yawar Amin
GitHub, Reddit, Twitter: yawaramin

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
!#
(use-modules
  (ggspec lib)
  (ice-9 ftw))

(define (run-file fname)
  "Run all test suites found in the given file, and aggregate and return
  the number of passed and failed tests.

  Arguments
    fname: string: the name of the file to look in for test suites.

  Returns
    (list num-passes num-fails): same as in the suite function."
  (call-with-input-file
    fname
    (lambda (f)
      (let loop
        ((form (read f))
        (num-passes 0)
        (num-fails 0)
        (num-skips 0))

        (cond
          ((eof-object? form)
            (list num-passes num-fails num-skips))
          ((equal? (car form) 'suite)
            ;; Run the current test suite.
            (let ((results (eval form (current-module))))
              (loop
                (read f)
                (+ num-passes (car results))
                (+ num-fails (cadr results))
                (+ num-skips (caddr results)))))
          (#t
            ;; This is some form other than a suite definition.
            (begin
              (eval form (current-module))
              ;; Go on to the next form, with results unchanged.
              (loop (read f) num-passes num-fails num-skips))))))))

(define (run-tree dname)
  "Run all test suites found in files in the given directory and all its
  subdirectories, and aggregate and return the number of passed and
  failed tests.

  Arguments
    dname: string: the name of the directory to look in for test suites.

  Returns
    (list num-passes num-fails): same as in the suite function."
  (define passed 0)
  (define failed 0)
  (define skipped 0)

  (nftw
    dname
    (lambda (filename statinfo flag base level)
      (define filename-length (string-length filename))

      (if (equal? (substring filename (- filename-length 4)) ".scm")
        (let ((file-results (run-file filename)))
          (set! passed (+ passed (car file-results)))
          (set! failed
            (+ failed (cadr file-results)))
          (set! skipped
            (+ skipped (caddr file-results)))))

      #t))

  (list passed failed skipped))

(define (main)
  (define result (run-tree "spec"))

  (println
    "Total "
    (apply + result)
    ", passed "
    (car result)
    ", failed "
    (cadr result)
    ", skipped "
    (caddr result)
    "."))

(main)

;; vim:set ft=scheme:

